module "aurora" {
  source                             = "./modules/aurora"
  name                               = var.aurora_name
  engine                             = var.engine
  engine_version                     = var.engine_version
  subnets                            = var.database_subnets
  vpc_id                             = var.vpc_id
  apply_immediately                  = var.apply_immediately
  publicly_accessible                = var.publicly_accessible
  skip_final_snapshot                = var.skip_final_snapshot
  allowed_cidr_blocks                = var.allowed_cidr_blocks
  create_security_group              = var.create_security_group
  database_name                      = var.database_name
  master_username                    = var.username
  master_password                    = var.password
  port                               = var.aurora_port
  monitoring_interval                = var.monitoring_interval
  auto_minor_version_upgrade         = var.auto_minor_version_upgrade
  scaling_configuration              = var.scaling_configuration
  storage_encrypted                  = var.storage_encrypted
  enable_http_endpoint               = var.enable_http_endpoint
  engine_mode                        = var.engine_mode
  security_group_description         = var.security_group_description
  copy_tags_to_snapshot              = var.copy_tags_to_snapshot
  instance_class                     = var.instance_class
  instances                          = var.instances
  serverlessv2_scaling_configuration = var.serverlessv2_scaling_configuration
  tags = {
    Application = "RDS"
    CreatedBy   = "terraform"
    Environment = "staging"
    Name        = "babelfish"
  }
}